feat: add onComplete param to popWhile function in RouterExt.kt
arkivanov/Decompose pull request #104
Opened 2022-05-13 11:47 UTC by Tommyten

Concerning [this](https://github.com/arkivanov/Decompose/issues/98) issue

2022-05-13 15:56 UTC, arkivanov requested changes

2022-05-13 15:56 UTC, arkivanov commented on decompose/src/commonMain/kotlin/com/arkivanov/decompose/router/RouterExt.kt
> + * The `isSuccess` argument is `true` if the stack size was greater than 1 and a component was popped,
This statement is not quite correct for this case. Would it be possible to change this to something like the following?

> The `isSuccess` argument is `true` if at least one component has been popped.

2022-05-13 16:25 UTC, arkivanov commented
Ahh, and could you please run `./gradlew apiDump` and commit the changes?

2022-05-13 18:04 UTC, Tommyten commented
Thank you for the suggestions, I've updated my branch

2022-05-13 19:07 UTC, arkivanov commented
Sorry, the sample master-detail doesn't compile. It's better to also allow the most common use case without `onComplete` callback: `router.popWhile {}`.

Perhaps we need two variants - the existing one as it is now, and the new one with all required arguments:

`router.popWhile(predicate)` and `router.popWhile(predicate, onComplete)`.

Do you want to update? Or alternatively I can do it in your branch. If you will update, please don't forget to rerun `apiDump` task at the end.

2022-05-13 19:12 UTC, arkivanov commented
So the existing function will delegate to the new one, similar to `Router.navigate` - https://github.com/arkivanov/Decompose/blob/96d08a3f0d8e67e36e466109b6b9a02e72dd1c67/decompose/src/commonMain/kotlin/com/arkivanov/decompose/router/RouterExt.kt#L9

2022-05-13 20:25 UTC, Tommyten commented
I will do it as soon as I get to my PC.
Sorry for the hassle 😅
I'm still getting used to the project but hoping to be involved more soon!

2022-05-13 20:31 UTC, arkivanov commented
Thanks for your contributions!

> Sorry for the hassle

I should have noticed this at the very beginning. :-)

2022-05-15 10:44 UTC, Tommyten commented
How about we just swap the parameters to be
```kotlin
inline fun <C : Any> Router<C, *>.popWhile(
    crossinline onComplete: (isSuccess: Boolean) -> Unit = {},
    crossinline predicate: (C) -> Boolean
) {
    navigate(
        transformer = { stack -> stack.dropLastWhile(predicate) },
        onComplete = { newStack, oldStack -> onComplete(newStack.size < oldStack.size) }
    )
}
```

This way the API would be backwards compatible. Although having the first parameter being optional is not always best practice, we could prevent having to overload `popWhile`. You call.

2022-05-15 10:57 UTC, arkivanov commented
> How about we just swap the parameters to be
> 
> ```kotlin
> inline fun <C : Any> Router<C, *>.popWhile(
>     crossinline onComplete: (isSuccess: Boolean) -> Unit = {},
>     crossinline predicate: (C) -> Boolean
> ) {
>     navigate(
>         transformer = { stack -> stack.dropLastWhile(predicate) },
>         onComplete = { newStack, oldStack -> onComplete(newStack.size < oldStack.size) }
>     )
> }
> ```
> 
> This way the API would be backwards compatible. Although having the first parameter being optional is not always best practice, we could prevent having to overload `popWhile`. You call.

There are a few points:

- I believe this change is still binary incompatible, it's only source compatible
- When using both arguments, it's looks intuitive to handle completion in the lambda outside parentheses
- There is already `Navigator.navigate(transformer, onComplete)` method, and an extension `Navigator.navigate(transformer)`. This was done like this for the reason mentioned above. Would be good to keep `popWhile` aligned.

2022-05-15 11:57 UTC, arkivanov commented
There is a build error:

> API check failed for project decompose.

Could you please run `./gradlew :decompose:apiDump` and commit the changes?

2022-05-15 13:57 UTC, arkivanov approved these changes

2022-05-15 13:57 UTC, merged

2022-05-15 13:57 UTC, arkivanov commented
Thanks for the contribution!