Grouped Decompose Helpers for iOS
arkivanov/Decompose pull request #373
Opened 2023-04-15 20:58 UTC by ttypic

Proposal to group Decompose specific helpers in iOS example.

@arkivanov What do you think?

2023-04-15 21:20 UTC, arkivanov commented
Yeah, I like it! We should also update any links in the docs.

Also, is it common to name folders with spaces?

2023-04-15 21:47 UTC, ttypic commented
Great, I am happy you like the idea!

> We should also update any links in the docs.

you are absolutely right, that's why it is in draft now. I will update all docs tomorrow. 

> Also, is it common to name folders with spaces?

I saw it in several projects and official examples, but I guess PascalCase is much more common and will look nicer in urls. I will rename.

2023-04-16 20:32 UTC, arkivanov requested changes

2023-04-16 20:32 UTC, arkivanov commented on docs/component/overview.md
> +
Let's add a separate section title here, e.g. "#### More Swift utilities".

2023-04-16 20:32 UTC, arkivanov commented on docs/component/overview.md
> +* [SimpleChildStack](https://github.com/arkivanov/Decompose/blob/master/sample/app-ios/app-ios/DecomposeHelpers/SimpleChildStack.swift) - helps to stub Decompose's `ChildStack` for Preview Components
Incorrect path here? `https://github.com/arkivanov/Decompose/blob/master/sample/app-ios/app-ios/DecomposeHelpers/CountersView.swift`

2023-04-16 20:32 UTC, arkivanov commented on docs/getting-started/quick-start.md
> +You can find more useful utilities for SwiftUI in the [DecomposeHelpers/](https://github.com/arkivanov/Decompose/blob/master/sample/app-ios/app-ios/DecomposeHelpers) folder:
It looks like a lot of information in quick start docs, I would rather keep only most essential information here. Maybe remove additional things for now? We already have this information in the Component overview page.

2023-04-16 21:43 UTC, merged

2023-04-16 21:43 UTC, arkivanov commented
Thank you!