Added direction parameter for the `slide` animation
arkivanov/Decompose pull request #442
Opened 2023-08-06 20:45 UTC by DATL4G

This **non-breaking** change adds the possibility to change the `slide` animation direction.
The default animation is `EndToStart` which results in the same as the previous implementation

2023-08-07 08:51 UTC, arkivanov commented
Thanks for the PR! The idea looks useful. Let me think about the API for a few days, I will post updates here.

> This non-breaking change

Adding a function parameter with a default value is a binary incompatible change (see [docs](https://kotlinlang.org/docs/jvm-api-guidelines-backward-compatibility.html#don-t-add-arguments-to-existing-api-functions)). In this case, we should add a new function with the new parameter (with default value), and then deprecate the old one with `Level.HIDDEN` and let it call the new variant.

Also, all API changes should only be released with a minor version bump. The next minor release will be `2.1.0`, currently in alpha (`2.1.0-alpha-06`). So this change should be done on [v2.1](https://github.com/arkivanov/Decompose/tree/v2.1) branch.

2023-08-07 11:39 UTC, DATL4G commented
Aight let me know when I have to change something

2023-08-09 15:57 UTC, arkivanov commented
Thanks for your patience. What do you think about utilising the existing `androidx.compose.foundation.gestures.Orientation` in the following way?

```kotlin
fun slide(
    animationSpec: FiniteAnimationSpec<Float> = tween(),
    orientation: Orientation = Orientation.Horizontal,
): StackAnimator
```

As of inversion, perhaps it could be implemented in general for `StackAnimator`. Something similar to what we [have in the sample](https://github.com/arkivanov/Decompose/blob/6aeaece9b8fec2b9e77d8942b775b78c91caf2ad/sample/shared/compose/src/commonMain/kotlin/com/arkivanov/sample/shared/root/RootContent.kt#L148) (currently disabled), but with better name. In a separate PR.

2023-08-09 20:22 UTC, DATL4G commented
I kinda like that, however I think it's too little configurable.

I have the use-case for example that certain screen destinations should come in from top and all other destinations are just fading.

So I configure it like this:

```kotlin
stackAnimation { child ->
	when (child.configuration) {
		is ScreenConfig.A, is ScreenConfig.B -> {
			slide(
				animationSpec,
				SlideDirection.TopToBottom
			)
		}
		else -> fade()
	}
}
```

I could easily swap the "current" `SlideDirection` with the `Orientation.Vertical` but how to specify that it should come from top?
Is the default configuration for `Orientation.Horizontal` from **right -> left**?
And the default configuration for `Orientation.Vertical` from **bottom -> top**?
Then we could do this with the `flip` method you mentioned but may be confusing for other users.

### Soo as I said I kinda like the idea

But maybe you could elaborate a bit more what your thoughts are about implementation and default configurations.

2023-08-09 20:30 UTC, arkivanov commented
> Then we could do this with the flip method you mentioned but may be confusing for other users.

Exactly. The idea is to add an extension separately, e.g. (the name is just a draft) `fun StackAnimator.reverse(): StackAnimator`. Then you can use it as follows.

```kotlin
stackAnimation { child ->
	when (child.configuration) {
		is ScreenConfig.A, is ScreenConfig.B -> slide(animationSpec, Orientation.Vertical).reverse()
		else -> fade()
	}
}
```

This would allow reversing any `StackAnimator`, not just `slide`.

2023-08-09 20:31 UTC, DATL4G commented
Alright I like that, sounds good!

2023-08-09 21:08 UTC, DATL4G commented
I applied the changes.

All needed to reverse the animation is to invert the factor, but I guess you're already thinking about an implementation for the discussed method.

2023-08-10 14:41 UTC, arkivanov requested changes

2023-08-10 14:41 UTC, arkivanov commented on extensions-compose-jetbrains/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/jetbrains/stack/animation/Slide.kt
> -private fun Modifier.offsetXFactor(factor: Float): Modifier =
Let's just add another `Modifier.offsetYFactor(float: Float): Modifier` method and switch one in `slide` function above. This would also avoid `Pair` allocations on each animation frame.

2023-08-10 14:41 UTC, arkivanov commented on extensions-compose-jetbrains/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/jetbrains/stack/animation/Slide.kt
> +fun slide(
As discussed earlier, this is currently a breaking API change. We have to deprecate the old method with `Level = HIDDEN` and just call the new method from there.

2023-08-10 14:42 UTC, arkivanov commented
As discussed earlier, please also move this change to the `v2.1` branch. Perhaps, this PR has to be closed and a new one opened.

2023-08-10 20:01 UTC, DatL4g commented
Done.
Contains your previous commits to master in documentation now but I guess that's not a problem

2023-08-10 23:17 UTC, arkivanov commented
> Contains your previous commits to master 

Sorry, but it would be nice to keep the PR clean. Can we avoid unnecessary commits and only include relevant changes?

2023-08-10 23:28 UTC, DATL4G commented
I think I can't exclude these commits since they are auto-added.
I could do a new PR if you want and bothers you

2023-08-11 00:52 UTC, arkivanov commented
Kindly, do a new PR. Let's keep the history clean, and PRs easily revertable.

2023-08-11 11:55 UTC, closed without merging