Rebase new slide method on 2.1 branch
arkivanov/Decompose pull request #446
Opened 2023-08-11 12:03 UTC by DATL4G

Reference: #442

2023-08-11 12:28 UTC, arkivanov requested changes
Could you please also run `./gradlew apiDump` and commit updated API files. Otherwise, build will fail.

2023-08-11 12:28 UTC, arkivanov commented on extensions-compose-jetbrains/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/jetbrains/stack/animation/Slide.kt
> +    replaceWith = ReplaceWith(
`replaceWith` shouldn't be required, because the method is hidden and can't be called. The new method will be used automatically.

2023-08-11 14:23 UTC, DATL4G commented
Done.

2023-08-11 14:31 UTC, arkivanov commented
Thanks for updating API files! The API diff shows that `com/arkivanov/decompose/extensions/compose/jetbrains/stack/animation/ComposableSingletons$SlideKt` got removed. I will need to check why this happened. This may be a binary incompatible change.

2023-08-12 15:19 UTC, arkivanov commented
I have pushed a fix to your branch so that `ComposableSingletons$SlideKt` is not removed. I'm not sure why it is part of the public API, looks like a bug, filed https://issuetracker.google.com/issues/295536730. But it's better to keep the class to avoid any binary compatibility issues.

Thanks for your contributions!

2023-08-12 15:19 UTC, merged